title : BasePlate Admin Blog
author :
  name : BasePlate-Admin
  email : zarifahnaf@outlook.com
  github : https://github.com/baseplate-admin
  twitter : nil
  feedburner : nil
  production_url : https://baseplate-admin.github.io/site
