[input]
url_prefix = "https://baseplate-admin.github.io/blog"
html_selector = "main"
base_directory = "output"

[[input.files]]
path = "how-to-make-a-permission_required-decorator-for-django-ninja.html"
url = "/how-to-make-a-permission_required-decorator-for-django-ninja"
title = "How to make a permission_required decorator for django-ninja"

[[input.files]]
path = "why-i-chose-django-ninja-instead-of-django-rest-framework-to-build-coreproject.html"
url = "/why-i-chose-django-ninja-instead-of-django-rest-framework-to-build-coreproject.html"
title = "Why I chose django-ninja instead of django-rest-framework to build coreproject"

[[input.files]]
path = "how-i-recreated-svelte-blur-effect-using-alpinejs-and-tailwindcss.html"
url = "/how-i-recreated-svelte-blur-effect-using-alpinejs-and-tailwindcss.html"
title = "How I recreated svelte blur effect using alpinejs and tailwind.css"

[[input.files]]
path = "how-i-added-daphne-server-dectection-to-wappalyzer.html"
url = "/how-i-added-daphne-server-dectection-to-wappalyzer.html"
title = "How I added daphne server dectection to wappalyzer"

[[input.files]]
path = "how-i-lost-my-first-pc.html"
url = "/how-i-lost-my-first-pc.html"
title = "How I lost my first PC"

[[input.files]]
path = "how-i-fell-in-love-with-honeyworks.html"
url = "/how-i-fell-in-love-with-honeyworks.html"
title = "How I fell in love with Honeyworks"

[[input.files]]
path = "how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
url = "/how-i-fixed-htmx-redeclaration-of-let-element-with-hx-boosttrue.html"
title = "How I fixed htmx redeclaration of let element with hx-boost=true"
